import asyncio, json
from playwright.async_api import async_playwright
from pathlib import Path
URL=(Path(__file__).resolve().parents[1]/"dist"/"DnD Spell Book.html").as_uri()
FIX=Path(__file__).resolve().parent/"fixtures"
import tempfile; SHOTS=Path(tempfile.gettempdir())/"spellbook-tests"; SHOTS.mkdir(exist_ok=True)
def ok(c,m): print(('OK  ' if c else 'FAIL'),m)
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch()
        pg=await (await b.new_context(viewport={'width':1360,'height':900},reduced_motion='reduce')).new_page()
        errs=[]; pg.on('pageerror',lambda e:errs.append(str(e)))
        ls=lambda k: pg.evaluate(f"JSON.parse(localStorage.getItem('{k}'))")
        await pg.goto(URL); await pg.wait_for_timeout(200)
        await pg.click('.spine[data-key="newchar:"]'); await pg.wait_for_timeout(200)
        ok(await pg.locator('.charbook .bm-sheet[aria-selected=true]').count()==1,'nowa postać: otwarta Karta postaci')
        ok(await pg.evaluate("document.activeElement.classList.contains('name')"),'kursor w polu imienia')
        ok(await pg.locator('.charbook .bm:not(.bm-sheet):not(:disabled)').count()==0,'pusta księga: zakładki poziomów wyłączone')
        ok(await pg.locator('#detail [data-goto]').count()==1,'prawa strona: zachęta do księgi klasy')
        await pg.select_option('[data-k=cls]','wizard'); await pg.wait_for_timeout(100)
        await pg.fill('[data-k=lvl]','5'); await pg.press('[data-k=lvl]','Tab'); await pg.wait_for_timeout(100)
        ok('0/9' in await pg.inner_text('.charbook .stats'),'statystyki na karcie (0/9 przygotowanych)')
        sl=await pg.inner_text('.slot-table'); print(sl.replace('\n',' | '))
        ok('4' in sl and '3' in sl and '2' in sl,'tabela slotów Wizard 5: 4/3/2')
        # dodaj zaklęcia z księgi klasy
        await pg.click('[data-goto]'); await pg.wait_for_timeout(150)
        for i in range(3): await pg.locator('#sh-list [data-toggle]').nth(i).click(); await pg.wait_for_timeout(50)
        await pg.click('.bm[data-lv="3"]'); await pg.wait_for_timeout(150)
        for i in range(2): await pg.locator('#sh-list [data-toggle]').nth(i).click(); await pg.wait_for_timeout(50)
        cid=(await ls('dndsb:ver:2024'))['chars'][0]['id']
        await pg.click(f'.spine[data-key="char:{cid}"]'); await pg.wait_for_timeout(200)
        cnt=await pg.evaluate("[...document.querySelectorAll('.charbook .bm:not(.bm-sheet):not(.bm-rib)')].map(b=>b.disabled?0:+b.querySelector('.bm-n').textContent)")
        ok(cnt==[3,0,0,2,0,0,0,0,0,0],f'zakładki postaci: C=3, 3=2 ({cnt})')
        toc=await pg.inner_text('.toc'); ok('Cantrips' in toc and 'Poziom 3' in toc,'spis zaklęć na karcie')
        await pg.fill('[data-k=notes]','Podklasa: Evoker'); await pg.locator('[data-k=notes]').blur(); await pg.wait_for_timeout(100)
        ok((await ls('dndsb:ver:2024'))['chars'][0]['notes']=='Podklasa: Evoker','notatki zapisane')
        # spis -> zakładka 3
        await pg.click('.toc-row[data-toc="3"]'); await pg.wait_for_timeout(150)
        ok(await pg.locator('.charbook .bm[aria-selected=true]').get_attribute('data-lv')=='3','kliknięcie w spisie przechodzi do zakładki 3')
        ok(await pg.locator('#cb-left .book-row').count()==2 and 'Przygotowane na tym poziomie: 2 z 2' in await pg.inner_text('#cb-left'),'lista poziomu 3 z licznikiem przygotowanych')
        await pg.locator('#cb-left .nm').first.click(); await pg.wait_for_timeout(100)
        ok(await pg.locator('#detail .card').count()==1 and await pg.locator('#detail [data-act=rm-book]').count()==1,'karta zaklęcia na prawej stronie z „Usuń z księgi”')
        await pg.locator('#cb-left [data-prep]').first.uncheck(); await pg.wait_for_timeout(100)
        ok('1 z 2' in await pg.inner_text('#cb-left'),'odznaczenie przygotowania')
        # usunięcie obu z poziomu 3 -> powrót do karty
        for _ in range(2): await pg.locator('#cb-left [data-rm]').first.click(); await pg.wait_for_timeout(120)
        ok(await pg.locator('.charbook .bm-sheet[aria-selected=true]').count()==1,'po usunięciu ostatniego zaklęcia z poziomu: powrót do karty')
        await pg.click('#toast button'); await pg.wait_for_timeout(150)
        ok(await pg.locator('.charbook .bm[data-lv="3"]').is_enabled(),'Cofnij przywraca zakładkę 3')
        # dodaj z księgi klasy -> na tym samym poziomie
        await pg.click('.charbook .bm[data-lv="3"]'); await pg.wait_for_timeout(150)
        await pg.click('[data-more]'); await pg.wait_for_timeout(200)
        ok((await ls('dndsb:app'))['open']=={'kind':'class','id':'wizard'} and await pg.locator('.bm[aria-selected=true]').get_attribute('data-lv')=='3','„Dodaj z księgi klasy” otwiera Wizard na poziomie 3')
        # pamięć zakładki
        await pg.click(f'.spine[data-key="char:{cid}"]'); await pg.wait_for_timeout(200)
        ok(await pg.locator('.charbook .bm[aria-selected=true]').get_attribute('data-lv')=='3','postać pamięta otwartą zakładkę')
        await pg.screenshot(path=str(SHOTS/'cb1.png'))
        await pg.click('.charbook .bm-sheet'); await pg.wait_for_timeout(150)
        await pg.screenshot(path=str(SHOTS/'cb2.png'))
        # animacja między zakładkami (bez ograniczenia ruchu)
        a=await (await b.new_context(viewport={'width':1360,'height':900})).new_page()
        a.on('pageerror',lambda e:errs.append(str(e)))
        st=await pg.evaluate("({a:localStorage.getItem('dndsb:app'),v:localStorage.getItem('dndsb:ver:2024')})")
        await a.goto(URL); await a.evaluate(f"localStorage.setItem('dndsb:app',{json.dumps(st['a'])});localStorage.setItem('dndsb:ver:2024',{json.dumps(st['v'])})"); await a.reload(); await a.wait_for_timeout(300)
        await a.click('.charbook .bm[data-lv="3"]'); await a.wait_for_timeout(150)
        ok(await a.locator('.pt-overlay .pt-leaf').count()==4,'karta → poziom 3: cztery kartki (wachlarz)')
        await a.wait_for_timeout(1500)
        ok(await a.locator('.pt-overlay').count()==0 and await a.locator('.charbook .bm[aria-selected=true]').get_attribute('data-lv')=='3','po animacji zakładka 3')
        # wąski ekran
        m=await (await b.new_context(viewport={'width':390,'height':800},reduced_motion='reduce')).new_page()
        m.on('pageerror',lambda e:errs.append(str(e)))
        await m.goto(URL); await m.evaluate(f"localStorage.setItem('dndsb:app',{json.dumps(st['a'])});localStorage.setItem('dndsb:ver:2024',{json.dumps(st['v'])})"); await m.reload(); await m.wait_for_timeout(300)
        ok(await m.locator('#detail .slot-table').is_visible() and await m.locator('#detail textarea').is_visible(),'telefon: sloty i notatki widoczne na karcie postaci')
        ok(await m.evaluate("document.documentElement.scrollWidth<=innerWidth"),'telefon: bez poziomego przewijania')
        await m.screenshot(path=str(SHOTS/'cb3.png'), full_page=True)
        print('BŁĘDY JS:',errs); await b.close()
asyncio.run(main())
