import asyncio, json
from playwright.async_api import async_playwright
from pathlib import Path
URL=(Path(__file__).resolve().parents[1]/"dist"/"DnD Spell Book.html").as_uri()
FIX=Path(__file__).resolve().parent/"fixtures"
import tempfile; SHOTS=Path(tempfile.gettempdir())/"spellbook-tests"; SHOTS.mkdir(exist_ok=True)
def ok(c,m): print(('OK  ' if c else 'FAIL'),m)
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch()
        pg=await (await b.new_context(viewport={'width':1360,'height':900})).new_page()
        errs=[]; pg.on('pageerror',lambda e:errs.append(str(e)))
        await pg.goto(URL); await pg.wait_for_timeout(200)
        await pg.evaluate("localStorage.setItem('dndsb:app',JSON.stringify({ver:'2024',open:{kind:'class',id:'druid'},theme:'auto'}))"); await pg.reload(); await pg.wait_for_timeout(400)
        # równe strony i stała wysokość
        dims=await pg.evaluate("[...document.querySelectorAll('.pages > .page')].map(p=>[Math.round(p.getBoundingClientRect().width),Math.round(p.getBoundingClientRect().height)])")
        ok(abs(dims[0][0]-dims[1][0])<=2 and dims[0][1]==dims[1][1],f'równe strony {dims}')
        fits=await pg.evaluate("document.documentElement.scrollHeight<=innerHeight+80")
        ok(fits,'księga mieści się w oknie (strona okna prawie bez przewijania)')
        h1=await pg.evaluate("document.querySelector('.pages').offsetHeight")
        await pg.click('.bm[data-lv="9"]'); await pg.wait_for_timeout(1700)
        h2=await pg.evaluate("document.querySelector('.pages').offsetHeight")
        ok(h1==h2,f'wysokość taka sama przy zakładce 9 (4 zaklęcia) i C ({h1} / {h2})')
        await pg.click('.spine[data-key="compendium:"]'); await pg.wait_for_timeout(1700)
        h3=await pg.evaluate("document.querySelector('.pages').offsetHeight")
        ok(abs(h3-h2)<60,f'Kompendium podobnej wysokości ({h3})')
        await pg.click('.bm[data-lv="1"]'); await pg.wait_for_timeout(1700)
        sc=await pg.evaluate("(()=>{const l=document.querySelector('.page.listcol');return [l.scrollHeight>l.clientHeight, getComputedStyle(l).overflowY]})()")
        ok(sc==[True,'auto'],'długa lista przewija się wewnątrz strony')
        await pg.evaluate("document.querySelector('.page.listcol').scrollTop=400"); await pg.wait_for_timeout(50)
        await pg.click('.bm[data-lv="2"]'); await pg.wait_for_timeout(200)
        st=await pg.evaluate("[...document.querySelectorAll('.pt-under .pt-page')].slice(0,1).map(c=>c.scrollTop)")
        ok(st and st[0]==400,f'kopia strony w animacji zachowuje przewinięcie ({st})')
        await pg.wait_for_timeout(1500)
        # odkładanie z animacją
        await pg.click('[data-home]'); await pg.wait_for_timeout(250)
        ok(await pg.locator('.open-anim .oa-book').count()==1,'odkładanie: nakładka z księgą')
        ok(await pg.locator('.bookcase:not(.compact)').count()==1,'regał rozwija się w trakcie')
        hid=await pg.evaluate("getComputedStyle(document.querySelector('.spine[data-key=\"compendium:\"]')).visibility")
        ok(hid=='hidden','prawdziwy grzbiet ukryty do lądowania')
        await pg.wait_for_timeout(500); await pg.screenshot(path=str(SHOTS/'cl1.png'))
        await pg.wait_for_timeout(400); await pg.screenshot(path=str(SHOTS/'cl2.png'))
        await pg.wait_for_timeout(900)
        ok(await pg.locator('.open-anim').count()==0 and await pg.evaluate("getComputedStyle(document.querySelector('.spine[data-key=\"compendium:\"]')).visibility")=='visible','po lądowaniu: nakładka usunięta, grzbiet widoczny')
        ok(json.loads(await pg.evaluate("localStorage.getItem('dndsb:app')"))['open'] is None,'stan: regał')
        # Esc i kliknięcie wysuniętej księgi
        await pg.click('.spine[data-key="class:bard"]'); await pg.wait_for_timeout(1500)
        await pg.mouse.move(700,800); await pg.keyboard.press('Escape'); await pg.wait_for_timeout(250)
        ok(await pg.locator('.open-anim').count()==1,'Esc: animacja odkładania')
        await pg.wait_for_timeout(1600)
        await pg.click('.spine[data-key="class:bard"]'); await pg.wait_for_timeout(1500)
        await pg.click('.spine[data-key="class:bard"]'); await pg.wait_for_timeout(250)
        ok(await pg.locator('.open-anim').count()==1,'kliknięcie wysuniętej księgi: animacja odkładania')
        await pg.wait_for_timeout(1600)
        # usunięcie postaci: bez animacji
        await pg.click('.spine[data-key="newchar:"]'); await pg.wait_for_timeout(300)
        await pg.click('[data-del]'); await pg.wait_for_timeout(120)
        ok(await pg.locator('.open-anim').count()==0 and await pg.locator('.bookcase:not(.compact)').count()==1,'usunięcie postaci: regał od razu')
        print('BŁĘDY JS:',errs); await b.close()
asyncio.run(main())
