import asyncio, json
from playwright.async_api import async_playwright
from pathlib import Path
URL=(Path(__file__).resolve().parents[1]/"dist"/"DnD Spell Book.html").as_uri()
FIX=Path(__file__).resolve().parent/"fixtures"
import tempfile; SHOTS=Path(tempfile.gettempdir())/"spellbook-tests"; SHOTS.mkdir(exist_ok=True)
def ok(c,m): print(('OK  ' if c else 'FAIL'),m)
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch()
        pg=await (await b.new_context(viewport={'width':1360,'height':900},reduced_motion='reduce')).new_page()
        errs=[]; pg.on('pageerror',lambda e:errs.append(str(e)))
        ls=lambda k: pg.evaluate(f"JSON.parse(localStorage.getItem('{k}'))")
        rib_vis=lambda key: pg.evaluate(f"!document.querySelector('.spine[data-key=\"{key}\"] .sp-ribbon').hidden")
        await pg.goto(URL); await pg.wait_for_timeout(200)
        # --- Własne zaklęcia: rozkładówka
        await pg.click('.spine[data-key="homebrew:"]'); await pg.wait_for_timeout(200)
        ok(await pg.locator('.hbbook .pages > .page').count()==2 and await pg.locator('.hbbook .bm').count()==11,'Własne zaklęcia: rozkładówka, zakładki Wstążki + C–9')
        ok(await pg.locator('.hbbook .bm:not(:disabled)').count()==0,'pusta księga: zakładki wyłączone')
        for nm,l in [('Iskra','0'),('Mgła','2'),('Tarcza','2')]:
            await pg.click('[data-new]'); await pg.fill('#h-n',nm); await pg.select_option('#h-l',l); await pg.click('#dlg [data-ok]'); await pg.wait_for_timeout(150)
        ok(await pg.locator('.hbbook .bm[aria-selected=true]').get_attribute('data-lv')=='2' and 'Tarcza' in await pg.inner_text('#detail'),'po zapisaniu: zakładka poziomu 2 i karta nowego zaklęcia')
        ok(await pg.locator('#hb-left .book-row').count()==2,'poziom 2: dwa zaklęcia')
        await pg.click('.hbbook .bm[data-lv="0"]'); await pg.wait_for_timeout(150)
        ok(await pg.locator('#hb-left .book-row').count()==1,'zakładka C: jedno zaklęcie')
        await pg.click('#hb-left [data-edit]'); await pg.wait_for_timeout(100); await pg.fill('#h-n','Iskra Wielka'); await pg.click('#dlg [data-ok]'); await pg.wait_for_timeout(150)
        ok('Iskra Wielka' in await pg.inner_text('#hb-left'),'edycja z wiersza')
        # wstążki w Własnych zaklęciach
        await pg.click('#hb-left [data-rib]'); await pg.wait_for_timeout(150)
        ok(await rib_vis('homebrew:'),'wstążka na grzbiecie „Własne zaklęcia”')
        ok(await pg.locator('.hbbook .bm-rib').is_enabled() and await pg.inner_text('.hbbook .bm-rib .bm-n')=='1','zakładka Wstążki: 1')
        await pg.click('.hbbook .bm-rib'); await pg.wait_for_timeout(150)
        ok('Iskra Wielka' in await pg.inner_text('#hb-left') and await pg.locator('#hb-left .book-subhead').count()==1,'lista Wstążki z nagłówkiem poziomu')
        await pg.click('#hb-left [data-rib]'); await pg.wait_for_timeout(150)
        ok(not await rib_vis('homebrew:') and await pg.locator('.hbbook .bm[aria-selected=true]').get_attribute('data-lv')!='-0.5','zdjęcie ostatniej wstążki: znika z grzbietu, księga opuszcza pustą zakładkę')
        # --- księga klasy
        await pg.click('.spine[data-key="class:wizard"]'); await pg.wait_for_timeout(200)
        await pg.click('.bm[data-lv="3"]'); await pg.wait_for_timeout(150)
        for sid in ['fireball','counterspell']:
            await pg.click(f'#sh-list .spell-row[data-id="{sid}"] [data-rib]'); await pg.wait_for_timeout(80)
        await pg.click('.bm[data-lv="1"]'); await pg.wait_for_timeout(150)
        await pg.click('#sh-list .spell-row[data-id="shield"] [data-rib]'); await pg.wait_for_timeout(80)
        ok(await rib_vis('class:wizard') and await pg.inner_text('.bm-rib .bm-n')=='3','Wizard: 3 wstążki, wstążka na grzbiecie')
        await pg.click('.bm-rib'); await pg.wait_for_timeout(150)
        heads=await pg.locator('#sh-list .lvl-head').all_inner_texts(); rows=await pg.evaluate("[...document.querySelectorAll('#sh-list .spell-row')].map(r=>r.dataset.id)")
        ok(heads==['Poziom 1','Poziom 3'] and rows==['shield','counterspell','fireball'],f'zakładka Wstążki: pogrupowane ({heads}, {rows})')
        ok(not await rib_vis('class:druid'),'Druid bez wstążki (osobne księgi)')
        # --- Kompendium
        await pg.click('.spine[data-key="compendium:"]'); await pg.wait_for_timeout(200)
        await pg.fill('#q','bless'); await pg.wait_for_timeout(300)
        await pg.click('#list .spell-row[data-id="bless"] [data-rib]'); await pg.wait_for_timeout(100)
        ok(await rib_vis('compendium:'),'Kompendium: wstążka na grzbiecie')
        await pg.fill('#q',''); await pg.wait_for_timeout(300)
        ok(await pg.inner_text('#c-vols .bm-rib .bm-n')=='1','Kompendium: zakładka Wstążki (1)')
        await pg.fill('#q','zzz'); await pg.wait_for_timeout(300)
        ok(await pg.inner_text('#c-vols .bm-rib .bm-n')=='0','filtry zmieniają licznik wstążek')
        await pg.fill('#q',''); await pg.wait_for_timeout(300)
        # --- księga postaci
        await pg.click('.spine[data-key="newchar:"]'); await pg.wait_for_timeout(250)
        await pg.select_option('[data-k=cls]','wizard'); await pg.wait_for_timeout(100)
        cid=(await ls('dndsb:ver:2024'))['chars'][0]['id']
        await pg.click('.spine[data-key="class:wizard"]'); await pg.wait_for_timeout(200)
        await pg.click('.bm[data-lv="3"]'); await pg.wait_for_timeout(150)
        for sid in ['fireball','fly']: await pg.click(f'#sh-list .spell-row[data-id="{sid}"] [data-toggle]'); await pg.wait_for_timeout(60)
        await pg.click(f'.spine[data-key="char:{cid}"]'); await pg.wait_for_timeout(200)
        order=await pg.evaluate("[...document.querySelectorAll('.charbook .bm')].map(b=>b.dataset.lv)")
        ok(order[:3]==['-1','-0.5','0'],f'księga postaci: karta, Wstążki, C… ({order[:3]})')
        await pg.click('.charbook .bm[data-lv="3"]'); await pg.wait_for_timeout(150)
        await pg.click('#cb-left .book-row:has([data-open="fireball"]) [data-rib]'); await pg.wait_for_timeout(150)
        ok(await rib_vis(f'char:{cid}'),'księga postaci: wstążka na grzbiecie')
        s=await ls('dndsb:ver:2024'); ok(s['chars'][0]['ribbons']==['fireball'],'wstążki postaci zapisane w postaci')
        ok('"ribbons"' in await pg.evaluate("Settings.exportData(['2024'])"),'wstążki postaci w kopii zapasowej')
        await pg.click('.charbook .bm-rib'); await pg.wait_for_timeout(150)
        ok(await pg.locator('#cb-left .book-row').count()==1 and await pg.locator('#cb-left [data-more]').count()==0,'zakładka Wstążki: 1 zaklęcie, bez „Dodaj z księgi klasy”')
        await pg.click('#cb-left [data-rm]'); await pg.wait_for_timeout(150)
        s=await ls('dndsb:ver:2024'); ok('ribbons' not in s['chars'][0] and not await rib_vis(f'char:{cid}'),'usunięcie zaklęcia z księgi zdejmuje wstążkę')
        await pg.click('#toast button'); await pg.wait_for_timeout(150)
        s=await ls('dndsb:ver:2024'); ok(s['chars'][0].get('ribbons')==['fireball'],'Cofnij przywraca zaklęcie i wstążkę')
        await pg.click('[data-home]'); await pg.wait_for_timeout(200)
        await pg.screenshot(path=str(SHOTS/'rb1.png'))
        # przewracanie kartek do zakładki Wstążki (bez ograniczenia ruchu)
        a=await (await b.new_context(viewport={'width':1360,'height':900})).new_page()
        st=await pg.evaluate("({v:localStorage.getItem('dndsb:ver:2024')})")
        await a.goto(URL); await a.evaluate(f"localStorage.setItem('dndsb:ver:2024',{json.dumps(st['v'])});localStorage.setItem('dndsb:app',JSON.stringify({{ver:'2024',open:{{kind:'class',id:'wizard'}},theme:'auto'}}))"); await a.reload(); await a.wait_for_timeout(1300)
        await a.click('.bm[data-lv="5"]'); await a.wait_for_timeout(1600)
        await a.click('.bm-rib'); await a.wait_for_timeout(200)
        ok(await a.locator('.pt-overlay .pt-leaf').count()>=1,'przejście do Wstążek przewraca kartki (do tyłu)')
        await a.wait_for_timeout(1800)
        ok(await a.locator('.bm-rib[aria-selected=true]').count()==1,'po animacji: zakładka Wstążki')
        print('BŁĘDY JS:',errs); await b.close()
asyncio.run(main())
