import asyncio
from playwright.async_api import async_playwright
from pathlib import Path
URL=(Path(__file__).resolve().parents[1]/"dist"/"DnD Spell Book.html").as_uri()
FIX=Path(__file__).resolve().parent/"fixtures"
import tempfile; SHOTS=Path(tempfile.gettempdir())/"spellbook-tests"; SHOTS.mkdir(exist_ok=True)
def ok(c,m): print(('OK  ' if c else 'FAIL'),m)
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch(); pg=await (await b.new_context(viewport={'width':1360,'height':900},reduced_motion='reduce')).new_page()
        errs=[]; pg.on('pageerror',lambda e:errs.append(str(e)))
        await pg.goto(URL); await pg.wait_for_timeout(300)
        ls=lambda k: pg.evaluate(f"JSON.parse(localStorage.getItem('{k}'))")
        await pg.click('.spine[data-key="compendium:"]'); await pg.wait_for_timeout(200)
        await pg.fill('#q','fireball'); await pg.wait_for_timeout(300)
        ok(await pg.locator('#c-vols [aria-selected=true]').get_attribute('data-lv')=='3','Kompendium: wyszukanie przeskakuje do tomiku 3')
        await pg.select_option('[data-f=cls]','paladin'); await pg.fill('#q',''); await pg.wait_for_timeout(300)
        ok(await pg.locator('#c-vols .bm[data-lv="0"]').is_disabled(),'filtr klasy wyłącza puste tomiki')
        await pg.click('[data-clear]'); await pg.wait_for_timeout(100)
        await pg.click('.spine[data-key="newchar:"]'); await pg.wait_for_timeout(300)
        await pg.select_option('[data-k=cls]','wizard'); await pg.fill('[data-k=lvl]','5'); await pg.press('[data-k=lvl]','Tab'); await pg.wait_for_timeout(100)
        ok('0/9' in await pg.inner_text('.stats'),'Wizard 5: limit 9 przygotowanych')
        await pg.click('.spine[data-key="compendium:"]'); await pg.wait_for_timeout(200)
        for q in ['Fireball','Shield']:
            await pg.fill('#q',q); await pg.wait_for_timeout(250)
            await pg.locator(f'#list .spell-row:has(.nm:text-is("{q}")) [data-toggle]').click(); await pg.wait_for_timeout(80)
        cid=(await ls('dndsb:ver:2024'))['chars'][0]['id']
        await pg.click(f'.spine[data-key="char:{cid}"]'); await pg.wait_for_timeout(200)
        await pg.click('.charbook .bm[data-lv="1"]'); await pg.wait_for_timeout(150)
        await pg.locator('[data-prep=shield]').uncheck(); await pg.wait_for_timeout(100)
        await pg.click('.charbook .bm-sheet'); await pg.wait_for_timeout(150)
        ok('1/9' in await pg.inner_text('.stats'),'przygotowywanie w księdze postaci (zakładka 1 → karta 1/9)')
        await pg.click('.charbook .bm[data-lv="3"]'); await pg.wait_for_timeout(150)
        await pg.click('.nm[data-open=fireball]'); await pg.wait_for_timeout(100)
        ok('Fireball' in await pg.inner_text('#detail .card'),'karta zaklęcia na prawej stronie księgi postaci')
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(100)
        ok((await ls('dndsb:app'))['open'] is None,'Esc odkłada księgę postaci')
        await pg.click(f'.spine[data-key="char:{cid}"]'); await pg.wait_for_timeout(200)
        exp=await pg.evaluate("Settings.exportData(['2014','2024'])")
        await pg.click('.spine[data-key="settings:"]'); await pg.wait_for_timeout(200)
        await pg.click('[data-paste]'); await pg.fill('#imp-text',exp); await pg.click('[data-imp-text]'); await pg.wait_for_timeout(300)
        ok(await pg.locator('.spine[data-key^="char:"]').count()==2,'import dodaje księgę postaci na regał')
        await pg.click('#toast button'); await pg.wait_for_timeout(300)
        ok(await pg.locator('.spine[data-key^="char:"]').count()==1,'Cofnij import')
        await pg.click('[data-clear]'); await pg.click('#dlg [data-ok]'); await pg.wait_for_timeout(300)
        ok(await pg.locator('.spine[data-key^="char:"]').count()==0 and (await ls('dndsb:app'))['open']=={'kind':'settings'},'czyszczenie wersji usuwa księgi postaci; Ustawienia zostają otwarte')
        await pg.click('#toast button'); await pg.wait_for_timeout(300)
        ok(await pg.locator('.spine[data-key^="char:"]').count()==1,'Cofnij czyszczenie')
        await pg.click('input[value=dark]'); await pg.wait_for_timeout(100)
        await pg.click('.spine[data-key="settings:"]'); await pg.wait_for_timeout(600)
        await pg.screenshot(path=str(SHOTS/'r6.png'))
        print('BŁĘDY JS:',errs); await b.close()
asyncio.run(main())
